
export const columns = [
    "name",
    "Company",
    "Designation",
    "Age",
    "Experience",
    "Gender",
    "Mobile",
    "Email",
    "Faceook",
    "Gmail",
    "Google",
    "LinkedIn",
    "Whatsapp",
    "something",
]


export const data = [
    {
        "name": "",
        "Company": "",
        "Designation": "",
        "Age": "",
        "Experience": "",
        "Gender": "",
        "Mobile": "",
        "Email": "",
        "Faceook": "",
        "Gmail": "",
        "Google": "",
        "LinkedIn": "",
        "Whatsapp": "",
        "something": "",
    },
    {
        "name": "",
        "Company": "",
        "Designation": "",
        "Age": "",
        "Experience": "",
        "Gender": "",
        "Mobile": "",
        "Email": "",
        "Faceook": "",
        "Gmail": "",
        "Google": "",
        "LinkedIn": "",
        "Whatsapp": "",
        "something": "",
    },
    {
        "name": "",
        "Company": "",
        "Designation": "",
        "Age": "",
        "Experience": "",
        "Gender": "",
        "Mobile": "",
        "Email": "",
        "Faceook": "",
        "Gmail": "",
        "Google": "",
        "LinkedIn": "",
        "Whatsapp": "",
        "something": "",
    },
    {
        "name": "",
        "Company": "",
        "Designation": "",
        "Age": "",
        "Experience": "",
        "Gender": "",
        "Mobile": "",
        "Email": "",
        "Faceook": "",
        "Gmail": "",
        "Google": "",
        "LinkedIn": "",
        "Whatsapp": "",
        "something": "",
    },
    {
        "name": "",
        "Company": "",
        "Designation": "",
        "Age": "",
        "Experience": "",
        "Gender": "",
        "Mobile": "",
        "Email": "",
        "Faceook": "",
        "Gmail": "",
        "Google": "",
        "LinkedIn": "",
        "Whatsapp": "",
        "something": "",
    },
    {
        "name": "",
        "Company": "",
        "Designation": "",
        "Age": "",
        "Experience": "",
        "Gender": "",
        "Mobile": "",
        "Email": "",
        "Faceook": "",
        "Gmail": "",
        "Google": "",
        "LinkedIn": "",
        "Whatsapp": "",
        "something": "",
    },
    {
        "name": "",
        "Company": "",
        "Designation": "",
        "Age": "",
        "Experience": "",
        "Gender": "",
        "Mobile": "",
        "Email": "",
        "Faceook": "",
        "Gmail": "",
        "Google": "",
        "LinkedIn": "",
        "Whatsapp": "",
        "something": "",
    },
    {
        "name": "",
        "Company": "",
        "Designation": "",
        "Age": "",
        "Experience": "",
        "Gender": "",
        "Mobile": "",
        "Email": "",
        "Faceook": "",
        "Gmail": "",
        "Google": "",
        "LinkedIn": "",
        "Whatsapp": "",
        "something": "",
    },
    {
        "name": "",
        "Company": "",
        "Designation": "",
        "Age": "",
        "Experience": "",
        "Gender": "",
        "Mobile": "",
        "Email": "",
        "Faceook": "",
        "Gmail": "",
        "Google": "",
        "LinkedIn": "",
        "Whatsapp": "",
        "something": "",
    },
    {
        "name": "",
        "Company": "",
        "Designation": "",
        "Age": "",
        "Experience": "",
        "Gender": "",
        "Mobile": "",
        "Email": "",
        "Faceook": "",
        "Gmail": "",
        "Google": "",
        "LinkedIn": "",
        "Whatsapp": "",
        "something": "",
    },
    {
        "name": "",
        "Company": "",
        "Designation": "",
        "Age": "",
        "Experience": "",
        "Gender": "",
        "Mobile": "",
        "Email": "",
        "Faceook": "",
        "Gmail": "",
        "Google": "",
        "LinkedIn": "",
        "Whatsapp": "",
        "something": "",
    },
    {
        "name": "",
        "Company": "",
        "Designation": "",
        "Age": "",
        "Experience": "",
        "Gender": "",
        "Mobile": "",
        "Email": "",
        "Faceook": "",
        "Gmail": "",
        "Google": "",
        "LinkedIn": "",
        "Whatsapp": "",
        "something": "",
    },
    {
        "name": "",
        "Company": "",
        "Designation": "",
        "Age": "",
        "Experience": "",
        "Gender": "",
        "Mobile": "",
        "Email": "",
        "Faceook": "",
        "Gmail": "",
        "Google": "",
        "LinkedIn": "",
        "Whatsapp": "",
        "something": "",
    },
    {
        "name": "",
        "Company": "",
        "Designation": "",
        "Age": "",
        "Experience": "",
        "Gender": "",
        "Mobile": "",
        "Email": "",
        "Faceook": "",
        "Gmail": "",
        "Google": "",
        "LinkedIn": "",
        "Whatsapp": "",
        "something": "",
    },
    {
        "name": "aidfi d dfio ",
        "Company": "aidfi d dfio ",
        "Designation": "aidfi d dfio ",
        "Age": "aidfi d dfio ",
        "Experience": "aidfi d dfio ",
        "Gender": "aidfi d dfio ",
        "Mobile": "aidfi d dfio ",
        "Email": "aidfi d dfio ",
        "Faceook": "aidfi d dfio ",
        "Gmail": "aidfi d dfio ",
        "Google": "aidfi d dfio ",
        "LinkedIn": "aidfi d dfio ",
        "Whatsapp": "aidfi d dfio ",
        "something": "aidfi d dfio ",
    },
    {
        "name": "aidfi d dfio ",
        "Company": "aidfi d dfio ",
        "Designation": "aidfi d dfio ",
        "Age": "aidfi d dfio ",
        "Experience": "aidfi d dfio ",
        "Gender": "aidfi d dfio ",
        "Mobile": "aidfi d dfio ",
        "Email": "aidfi d dfio ",
        "Faceook": "aidfi d dfio ",
        "Gmail": "aidfi d dfio ",
        "Google": "aidfi d dfio ",
        "LinkedIn": "aidfi d dfio ",
        "Whatsapp": "aidfi d dfio ",
        "something": "aidfi d dfio ",
    },
    {
        "name": "aidfi d dfio ",
        "Company": "aidfi d dfio ",
        "Designation": "aidfi d dfio ",
        "Age": "aidfi d dfio ",
        "Experience": "aidfi d dfio ",
        "Gender": "aidfi d dfio ",
        "Mobile": "aidfi d dfio ",
        "Email": "aidfi d dfio ",
        "Faceook": "aidfi d dfio ",
        "Gmail": "aidfi d dfio ",
        "Google": "aidfi d dfio ",
        "LinkedIn": "aidfi d dfio ",
        "Whatsapp": "aidfi d dfio ",
        "something": "aidfi d dfio ",
    },
    {
        "name": "aidfi d dfio ",
        "Company": "aidfi d dfio ",
        "Designation": "aidfi d dfio ",
        "Age": "aidfi d dfio ",
        "Experience": "aidfi d dfio ",
        "Gender": "aidfi d dfio ",
        "Mobile": "aidfi d dfio ",
        "Email": "aidfi d dfio ",
        "Faceook": "aidfi d dfio ",
        "Gmail": "aidfi d dfio ",
        "Google": "aidfi d dfio ",
        "LinkedIn": "aidfi d dfio ",
        "Whatsapp": "aidfi d dfio ",
        "something": "aidfi d dfio ",
    },
    {
        "name": "aidfi d dfio ",
        "Company": "aidfi d dfio ",
        "Designation": "aidfi d dfio ",
        "Age": "aidfi d dfio ",
        "Experience": "aidfi d dfio ",
        "Gender": "aidfi d dfio ",
        "Mobile": "aidfi d dfio ",
        "Email": "aidfi d dfio ",
        "Faceook": "aidfi d dfio ",
        "Gmail": "aidfi d dfio ",
        "Google": "aidfi d dfio ",
        "LinkedIn": "aidfi d dfio ",
        "Whatsapp": "aidfi d dfio ",
        "something": "aidfi d dfio ",
    },
    {
        "name": "aidfi d dfio ",
        "Company": "aidfi d dfio ",
        "Designation": "aidfi d dfio ",
        "Age": "aidfi d dfio ",
        "Experience": "aidfi d dfio ",
        "Gender": "aidfi d dfio ",
        "Mobile": "aidfi d dfio ",
        "Email": "aidfi d dfio ",
        "Faceook": "aidfi d dfio ",
        "Gmail": "aidfi d dfio ",
        "Google": "aidfi d dfio ",
        "LinkedIn": "aidfi d dfio ",
        "Whatsapp": "aidfi d dfio ",
        "something": "aidfi d dfio ",
    },
    {
        "name": "aidfi d dfio ",
        "Company": "aidfi d dfio ",
        "Designation": "aidfi d dfio ",
        "Age": "aidfi d dfio ",
        "Experience": "aidfi d dfio ",
        "Gender": "aidfi d dfio ",
        "Mobile": "aidfi d dfio ",
        "Email": "aidfi d dfio ",
        "Faceook": "aidfi d dfio ",
        "Gmail": "aidfi d dfio ",
        "Google": "aidfi d dfio ",
        "LinkedIn": "aidfi d dfio ",
        "Whatsapp": "aidfi d dfio ",
        "something": "aidfi d dfio ",
    },
    {
        "name": "aidfi d dfio ",
        "Company": "aidfi d dfio ",
        "Designation": "aidfi d dfio ",
        "Age": "aidfi d dfio ",
        "Experience": "aidfi d dfio ",
        "Gender": "aidfi d dfio ",
        "Mobile": "aidfi d dfio ",
        "Email": "aidfi d dfio ",
        "Faceook": "aidfi d dfio ",
        "Gmail": "aidfi d dfio ",
        "Google": "aidfi d dfio ",
        "LinkedIn": "aidfi d dfio ",
        "Whatsapp": "aidfi d dfio ",
        "something": "aidfi d dfio ",
    },
    {
        "name": "aidfi d dfio ",
        "Company": "aidfi d dfio ",
        "Designation": "aidfi d dfio ",
        "Age": "aidfi d dfio ",
        "Experience": "aidfi d dfio ",
        "Gender": "aidfi d dfio ",
        "Mobile": "aidfi d dfio ",
        "Email": "aidfi d dfio ",
        "Faceook": "aidfi d dfio ",
        "Gmail": "aidfi d dfio ",
        "Google": "aidfi d dfio ",
        "LinkedIn": "aidfi d dfio ",
        "Whatsapp": "aidfi d dfio ",
        "something": "aidfi d dfio ",
    },
    {
        "name": "aidfi d dfio ",
        "Company": "aidfi d dfio ",
        "Designation": "aidfi d dfio ",
        "Age": "aidfi d dfio ",
        "Experience": "aidfi d dfio ",
        "Gender": "aidfi d dfio ",
        "Mobile": "aidfi d dfio ",
        "Email": "aidfi d dfio ",
        "Faceook": "aidfi d dfio ",
        "Gmail": "aidfi d dfio ",
        "Google": "aidfi d dfio ",
        "LinkedIn": "aidfi d dfio ",
        "Whatsapp": "aidfi d dfio ",
        "something": "aidfi d dfio ",
    },
    {
        "name": "aidfi d dfio ",
        "Company": "aidfi d dfio ",
        "Designation": "aidfi d dfio ",
        "Age": "aidfi d dfio ",
        "Experience": "aidfi d dfio ",
        "Gender": "aidfi d dfio ",
        "Mobile": "aidfi d dfio ",
        "Email": "aidfi d dfio ",
        "Faceook": "aidfi d dfio ",
        "Gmail": "aidfi d dfio ",
        "Google": "aidfi d dfio ",
        "LinkedIn": "aidfi d dfio ",
        "Whatsapp": "aidfi d dfio ",
        "something": "aidfi d dfio ",
    },
    {
        "name": "aidfi d dfio ",
        "Company": "aidfi d dfio ",
        "Designation": "aidfi d dfio ",
        "Age": "aidfi d dfio ",
        "Experience": "aidfi d dfio ",
        "Gender": "aidfi d dfio ",
        "Mobile": "aidfi d dfio ",
        "Email": "aidfi d dfio ",
        "Faceook": "aidfi d dfio ",
        "Gmail": "aidfi d dfio ",
        "Google": "aidfi d dfio ",
        "LinkedIn": "aidfi d dfio ",
        "Whatsapp": "aidfi d dfio ",
        "something": "aidfi d dfio ",
    },
    {
        "name": "aidfi d dfio ",
        "Company": "aidfi d dfio ",
        "Designation": "aidfi d dfio ",
        "Age": "aidfi d dfio ",
        "Experience": "aidfi d dfio ",
        "Gender": "aidfi d dfio ",
        "Mobile": "aidfi d dfio ",
        "Email": "aidfi d dfio ",
        "Faceook": "aidfi d dfio ",
        "Gmail": "aidfi d dfio ",
        "Google": "aidfi d dfio ",
        "LinkedIn": "aidfi d dfio ",
        "Whatsapp": "aidfi d dfio ",
        "something": "aidfi d dfio ",
    },
    {
        "name": "aidfi d dfio ",
        "Company": "aidfi d dfio ",
        "Designation": "aidfi d dfio ",
        "Age": "aidfi d dfio ",
        "Experience": "aidfi d dfio ",
        "Gender": "aidfi d dfio ",
        "Mobile": "aidfi d dfio ",
        "Email": "aidfi d dfio ",
        "Faceook": "aidfi d dfio ",
        "Gmail": "aidfi d dfio ",
        "Google": "aidfi d dfio ",
        "LinkedIn": "aidfi d dfio ",
        "Whatsapp": "aidfi d dfio ",
        "something": "aidfi d dfio ",
    },
    {
        "name": "aidfi d dfio ",
        "Company": "aidfi d dfio ",
        "Designation": "aidfi d dfio ",
        "Age": "aidfi d dfio ",
        "Experience": "aidfi d dfio ",
        "Gender": "aidfi d dfio ",
        "Mobile": "aidfi d dfio ",
        "Email": "aidfi d dfio ",
        "Faceook": "aidfi d dfio ",
        "Gmail": "aidfi d dfio ",
        "Google": "aidfi d dfio ",
        "LinkedIn": "aidfi d dfio ",
        "Whatsapp": "aidfi d dfio ",
        "something": "aidfi d dfio ",
    },
    {
        "name": "aidfi d dfio ",
        "Company": "aidfi d dfio ",
        "Designation": "aidfi d dfio ",
        "Age": "aidfi d dfio ",
        "Experience": "aidfi d dfio ",
        "Gender": "aidfi d dfio ",
        "Mobile": "aidfi d dfio ",
        "Email": "aidfi d dfio ",
        "Faceook": "aidfi d dfio ",
        "Gmail": "aidfi d dfio ",
        "Google": "aidfi d dfio ",
        "LinkedIn": "aidfi d dfio ",
        "Whatsapp": "aidfi d dfio ",
        "something": "aidfi d dfio ",
    },

    {
        "name": "aidfi d dfio ",
        "Company": "aidfi d dfio ",
        "Designation": "aidfi d dfio ",
        "Age": "aidfi d dfio ",
        "Experience": "aidfi d dfio ",
        "Gender": "aidfi d dfio ",
        "Mobile": "aidfi d dfio ",
        "Email": "aidfi d dfio ",
        "Faceook": "aidfi d dfio ",
        "Gmail": "aidfi d dfio ",
        "Google": "aidfi d dfio ",
        "LinkedIn": "aidfi d dfio ",
        "Whatsapp": "aidfi d dfio ",
        "something": "aidfi d dfio ",
    },
]
